// ============================================================================
// ALBION ONLINE TOOLS - MAIN CONFIGURATION
// ============================================================================

export type ServerType = 'west' | 'east' | 'europe';
export type ThemeType = 'dark' | 'light' | 'blue' | 'red' | 'green' | 'purple' | 'orange' | 'cyan' | 'pink' | 'gold' | 'midnight';
export type LanguageType = 'tr' | 'en' | 'de' | 'fr' | 'es' | 'ru' | 'pt' | 'it' | 'pl' | 'zh';

// ============================================================================
// API CONFIGURATION
// ============================================================================

export const API_BASE_URLS = {
  west: 'https://west.albion-online-data.com',
  east: 'https://east.albion-online-data.com',
  europe: 'https://europe.albion-online-data.com',
};

export const KILLBOARD_API_URL = 'https://albiononline.com/api/gameinfo';
export const ITEM_RENDER_URL = 'https://render.albiononline.com/v1/item';
export const GITHUB_RAW_URL = 'https://raw.githubusercontent.com/ao-data/ao-bin-dumps/master/formatted';

// ============================================================================
// SERVER CONFIGURATION
// ============================================================================

export interface ServerConfig {
  id: ServerType;
  name: string;
  nameLocalized: Record<LanguageType, string>;
  flag: string;
}

export const servers: ServerConfig[] = [
  {
    id: 'west',
    name: 'Americas (West)',
    nameLocalized: {
      tr: 'Amerika (Batı)',
      en: 'Americas (West)',
      de: 'Amerika (West)',
      fr: 'Amériques (Ouest)',
      es: 'Américas (Oeste)',
      ru: 'Америка (Запад)',
      pt: 'Américas (Oeste)',
      it: 'Americhe (Ovest)',
      pl: 'Ameryka (Zachód)',
      zh: '美洲 (西部)',
    },
    flag: '🇺🇸',
  },
  {
    id: 'east',
    name: 'Asia (East)',
    nameLocalized: {
      tr: 'Asya (Doğu)',
      en: 'Asia (East)',
      de: 'Asien (Ost)',
      fr: 'Asie (Est)',
      es: 'Asia (Este)',
      ru: 'Азия (Восток)',
      pt: 'Ásia (Leste)',
      it: 'Asia (Est)',
      pl: 'Azja (Wschód)',
      zh: '亚洲 (东部)',
    },
    flag: '🇯🇵',
  },
  {
    id: 'europe',
    name: 'Europe',
    nameLocalized: {
      tr: 'Avrupa',
      en: 'Europe',
      de: 'Europa',
      fr: 'Europe',
      es: 'Europa',
      ru: 'Европа',
      pt: 'Europa',
      it: 'Europa',
      pl: 'Europa',
      zh: '欧洲',
    },
    flag: '🇪🇺',
  },
];

// ============================================================================
// THEME CONFIGURATION
// ============================================================================

export interface ThemeConfig {
  id: ThemeType;
  name: string;
  nameLocalized: Record<LanguageType, string>;
  colors: {
    background: string;
    surface: string;
    surfaceHover: string;
    primary: string;
    primaryHover: string;
    secondary: string;
    accent: string;
    text: string;
    textMuted: string;
    border: string;
    success: string;
    warning: string;
    error: string;
    info: string;
  };
}

export const themes: ThemeConfig[] = [
  {
    id: 'dark',
    name: 'Dark',
    nameLocalized: {
      tr: 'Karanlık',
      en: 'Dark',
      de: 'Dunkel',
      fr: 'Sombre',
      es: 'Oscuro',
      ru: 'Тёмная',
      pt: 'Escuro',
      it: 'Scuro',
      pl: 'Ciemny',
      zh: '深色',
    },
    colors: {
      background: '#0a0a0f',
      surface: '#12121a',
      surfaceHover: '#1a1a25',
      primary: '#6366f1',
      primaryHover: '#818cf8',
      secondary: '#8b5cf6',
      accent: '#f59e0b',
      text: '#f8fafc',
      textMuted: '#94a3b8',
      border: '#27273a',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
    },
  },
  {
    id: 'light',
    name: 'Light',
    nameLocalized: {
      tr: 'Aydınlık',
      en: 'Light',
      de: 'Hell',
      fr: 'Clair',
      es: 'Claro',
      ru: 'Светлая',
      pt: 'Claro',
      it: 'Chiaro',
      pl: 'Jasny',
      zh: '浅色',
    },
    colors: {
      background: '#f8fafc',
      surface: '#ffffff',
      surfaceHover: '#f1f5f9',
      primary: '#4f46e5',
      primaryHover: '#4338ca',
      secondary: '#7c3aed',
      accent: '#d97706',
      text: '#0f172a',
      textMuted: '#64748b',
      border: '#e2e8f0',
      success: '#16a34a',
      warning: '#d97706',
      error: '#dc2626',
      info: '#2563eb',
    },
  },
  {
    id: 'blue',
    name: 'Ocean Blue',
    nameLocalized: {
      tr: 'Okyanus Mavisi',
      en: 'Ocean Blue',
      de: 'Ozeanblau',
      fr: 'Bleu Océan',
      es: 'Azul Océano',
      ru: 'Океанский Синий',
      pt: 'Azul Oceano',
      it: 'Blu Oceano',
      pl: 'Oceaniczny Niebieski',
      zh: '海洋蓝',
    },
    colors: {
      background: '#0c1a2d',
      surface: '#132238',
      surfaceHover: '#1a2d4a',
      primary: '#0ea5e9',
      primaryHover: '#38bdf8',
      secondary: '#6366f1',
      accent: '#06b6d4',
      text: '#e0f2fe',
      textMuted: '#7dd3fc',
      border: '#1e3a5f',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#0ea5e9',
    },
  },
  {
    id: 'red',
    name: 'Blood Red',
    nameLocalized: {
      tr: 'Kan Kırmızısı',
      en: 'Blood Red',
      de: 'Blutrot',
      fr: 'Rouge Sang',
      es: 'Rojo Sangre',
      ru: 'Кроваво-Красный',
      pt: 'Vermelho Sangue',
      it: 'Rosso Sangue',
      pl: 'Krwista Czerwień',
      zh: '血红',
    },
    colors: {
      background: '#1a0505',
      surface: '#2a0a0a',
      surfaceHover: '#3d0f0f',
      primary: '#dc2626',
      primaryHover: '#ef4444',
      secondary: '#991b1b',
      accent: '#f59e0b',
      text: '#fef2f2',
      textMuted: '#fca5a5',
      border: '#450a0a',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#dc2626',
      info: '#3b82f6',
    },
  },
  {
    id: 'green',
    name: 'Forest Green',
    nameLocalized: {
      tr: 'Orman Yeşili',
      en: 'Forest Green',
      de: 'Waldgrün',
      fr: 'Vert Forêt',
      es: 'Verde Bosque',
      ru: 'Лесной Зелёный',
      pt: 'Verde Floresta',
      it: 'Verde Foresta',
      pl: 'Leśna Zieleń',
      zh: '森林绿',
    },
    colors: {
      background: '#052e16',
      surface: '#064e3b',
      surfaceHover: '#065f46',
      primary: '#10b981',
      primaryHover: '#34d399',
      secondary: '#059669',
      accent: '#84cc16',
      text: '#ecfdf5',
      textMuted: '#6ee7b7',
      border: '#047857',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
    },
  },
  {
    id: 'purple',
    name: 'Mystic Purple',
    nameLocalized: {
      tr: 'Mistik Mor',
      en: 'Mystic Purple',
      de: 'Mystisches Lila',
      fr: 'Violet Mystique',
      es: 'Púrpura Místico',
      ru: 'Мистический Фиолетовый',
      pt: 'Roxo Místico',
      it: 'Viola Mistico',
      pl: 'Mistyczny Fiolet',
      zh: '神秘紫',
    },
    colors: {
      background: '#1e1b4b',
      surface: '#2e1065',
      surfaceHover: '#3b0764',
      primary: '#a855f7',
      primaryHover: '#c084fc',
      secondary: '#7c3aed',
      accent: '#e879f9',
      text: '#faf5ff',
      textMuted: '#d8b4fe',
      border: '#581c87',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
    },
  },
  {
    id: 'orange',
    name: 'Sunset Orange',
    nameLocalized: {
      tr: 'Gün Batımı Turuncusu',
      en: 'Sunset Orange',
      de: 'Sonnenuntergang Orange',
      fr: 'Orange Coucher de Soleil',
      es: 'Naranja Atardecer',
      ru: 'Закатный Оранжевый',
      pt: 'Laranja Pôr do Sol',
      it: 'Arancione Tramonto',
      pl: 'Pomarańczowy Zachód',
      zh: '日落橙',
    },
    colors: {
      background: '#2a1205',
      surface: '#3d1a0a',
      surfaceHover: '#4a200c',
      primary: '#f97316',
      primaryHover: '#fb923c',
      secondary: '#ea580c',
      accent: '#fbbf24',
      text: '#fff7ed',
      textMuted: '#fdba74',
      border: '#7c2d12',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
    },
  },
  {
    id: 'cyan',
    name: 'Cyber Cyan',
    nameLocalized: {
      tr: 'Siber Camgöbeği',
      en: 'Cyber Cyan',
      de: 'Cyber Cyan',
      fr: 'Cyan Cyber',
      es: 'Cian Cibernético',
      ru: 'Кибер-Бирюзовый',
      pt: 'Ciano Cyber',
      it: 'Ciano Cyber',
      pl: 'Cyber Cyjan',
      zh: '赛博青',
    },
    colors: {
      background: '#001a1a',
      surface: '#002b2b',
      surfaceHover: '#003d3d',
      primary: '#06b6d4',
      primaryHover: '#22d3ee',
      secondary: '#0891b2',
      accent: '#2dd4bf',
      text: '#ecfeff',
      textMuted: '#67e8f9',
      border: '#005c5c',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
    },
  },
  {
    id: 'pink',
    name: 'Neon Pink',
    nameLocalized: {
      tr: 'Neon Pembe',
      en: 'Neon Pink',
      de: 'Neon Pink',
      fr: 'Rose Néon',
      es: 'Rosa Neón',
      ru: 'Неоновый Розовый',
      pt: 'Rosa Neon',
      it: 'Rosa Neon',
      pl: 'Neonowy Róż',
      zh: '霓虹粉',
    },
    colors: {
      background: '#2a0a1a',
      surface: '#3d0f2a',
      surfaceHover: '#4a1233',
      primary: '#ec4899',
      primaryHover: '#f472b6',
      secondary: '#db2777',
      accent: '#fbbf24',
      text: '#fdf2f8',
      textMuted: '#fbcfe8',
      border: '#7c1d4f',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
    },
  },
  {
    id: 'gold',
    name: 'Royal Gold',
    nameLocalized: {
      tr: 'Kraliyet Altını',
      en: 'Royal Gold',
      de: 'Königliches Gold',
      fr: 'Or Royal',
      es: 'Oro Real',
      ru: 'Королевское Золото',
      pt: 'Ouro Real',
      it: 'Oro Reale',
      pl: 'Królewskie Złoto',
      zh: '皇家金',
    },
    colors: {
      background: '#1a1505',
      surface: '#2a2008',
      surfaceHover: '#3d2e0a',
      primary: '#eab308',
      primaryHover: '#facc15',
      secondary: '#ca8a04',
      accent: '#f59e0b',
      text: '#fefce8',
      textMuted: '#fde047',
      border: '#713f12',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
    },
  },
  {
    id: 'midnight',
    name: 'Midnight Black',
    nameLocalized: {
      tr: 'Gece Yarısı Siyahı',
      en: 'Midnight Black',
      de: 'Mitternachtsschwarz',
      fr: 'Noir Minuit',
      es: 'Negro Medianoche',
      ru: 'Полуночный Чёрный',
      pt: 'Preto Meia-Noite',
      it: 'Nero Mezzanotte',
      pl: 'Północna Czerń',
      zh: '午夜黑',
    },
    colors: {
      background: '#000000',
      surface: '#0a0a0a',
      surfaceHover: '#141414',
      primary: '#ffffff',
      primaryHover: '#e5e5e5',
      secondary: '#525252',
      accent: '#737373',
      text: '#ffffff',
      textMuted: '#a3a3a3',
      border: '#262626',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
    },
  },
];

// ============================================================================
// LANGUAGE CONFIGURATION
// ============================================================================

export const translations = {
  tr: {
    siteName: 'Albion Online Tools',
    siteDescription: 'Albion Online için kapsamlı araçlar ve rehberler',
    nav: {
      home: 'Ana Sayfa',
      market: 'Pazar',
      crafting: 'Crafting',
      maps: 'Haritalar',
      killboard: 'Killboard',
      builds: 'Buildler',
      calculator: 'Hesaplayıcı',
      settings: 'Ayarlar',
    },
    server: {
      title: 'Sunucu Seçimi',
      description: 'Verileri çekmek istediğiniz sunucuyu seçin',
    },
    theme: {
      title: 'Tema',
      description: 'Uygulama temasını değiştir',
    },
    language: {
      title: 'Dil',
      description: 'Uygulama dilini değiştir',
    },
    market: {
      title: 'Pazar Fiyatları',
      searchPlaceholder: 'Eşya ara...',
      search: 'Ara',
      city: 'Şehir',
      quality: 'Kalite',
      tier: 'Seviye',
      buyPrice: 'Alış Fiyatı',
      sellPrice: 'Satış Fiyatı',
      lastUpdate: 'Son Güncelleme',
      noData: 'Veri bulunamadı',
      loading: 'Yükleniyor...',
    },
    crafting: {
      title: 'Crafting Hesaplayıcı',
      selectItem: 'Eşya Seç',
      resources: 'Malzemeler',
      totalCost: 'Toplam Maliyet',
      profit: 'Kar',
      profitMargin: 'Kar Marjı',
      cityBonus: 'Şehir Bonusu',
      rrBonus: 'Kaynak İade Oranı',
    },
    maps: {
      title: 'Haritalar',
      avalon: 'Avalon Yolları',
      blackZone: 'Siyah Bölge',
      redZone: 'Kırmızı Bölge',
      yellowZone: 'Sarı Bölge',
      blueZone: 'Mavi Bölge',
      searchMap: 'Harita ara...',
      tier: 'Seviye',
      resources: 'Kaynaklar',
      hideouts: 'Hideoutlar',
      dungeons: 'Zindanlar',
      portals: 'Portallar',
      smartSort: 'Akıllı Sıralama',
      bestForCrafting: 'Crafting için en iyi',
      bestForGathering: 'Toplama için en iyi',
      bestForPvp: 'PvP için en iyi',
    },
    killboard: {
      title: 'Killboard',
      searchPlayer: 'Oyuncu ara...',
      searchGuild: 'Lonca ara...',
      searchAlliance: 'İttifak ara...',
      recentKills: 'Son Öldürmeler',
      topKills: 'En İyi Öldürmeler',
      soloKills: 'Solo Öldürmeler',
      battles: 'Savaşlar',
      fame: 'Şöhret',
      killFame: 'Öldürme Şöhreti',
      deathFame: 'Ölüm Şöhreti',
    },
    builds: {
      title: 'Build Önerileri',
      solo: 'Solo',
      group: 'Grup',
      dungeon: 'Zindan',
      pvp: 'PvP',
      pve: 'PvE',
      ganking: 'Ganking',
      gathering: 'Toplama',
      healing: 'Healing',
      tanking: 'Tanking',
      dps: 'DPS',
      support: 'Destek',
      aiRecommended: 'AI Önerisi',
      selectActivity: 'Aktivite Seç',
      selectGroupSize: 'Grup Boyutu',
      recommendedSet: 'Önerilen Set',
      alternatives: 'Alternatifler',
    },
    calculator: {
      title: 'Hesaplayıcılar',
      farming: 'Farming',
      laborers: 'İşçiler',
      refining: 'Rafine',
      journal: 'Günlük',
      nutrition: 'Besin',
      association: 'Birlik',
    },
    common: {
      save: 'Kaydet',
      cancel: 'İptal',
      delete: 'Sil',
      edit: 'Düzenle',
      create: 'Oluştur',
      search: 'Ara',
      filter: 'Filtre',
      sort: 'Sırala',
      refresh: 'Yenile',
      loading: 'Yükleniyor...',
      error: 'Hata',
      success: 'Başarılı',
      warning: 'Uyarı',
      info: 'Bilgi',
      close: 'Kapat',
      open: 'Aç',
      back: 'Geri',
      next: 'İleri',
      previous: 'Önceki',
      confirm: 'Onayla',
      yes: 'Evet',
      no: 'Hayır',
    },
  },
  en: {
    siteName: 'Albion Online Tools',
    siteDescription: 'Comprehensive tools and guides for Albion Online',
    nav: {
      home: 'Home',
      market: 'Market',
      crafting: 'Crafting',
      maps: 'Maps',
      killboard: 'Killboard',
      builds: 'Builds',
      calculator: 'Calculator',
      settings: 'Settings',
    },
    server: {
      title: 'Server Selection',
      description: 'Select the server to fetch data from',
    },
    theme: {
      title: 'Theme',
      description: 'Change application theme',
    },
    language: {
      title: 'Language',
      description: 'Change application language',
    },
    market: {
      title: 'Market Prices',
      searchPlaceholder: 'Search item...',
      search: 'Search',
      city: 'City',
      quality: 'Quality',
      tier: 'Tier',
      buyPrice: 'Buy Price',
      sellPrice: 'Sell Price',
      lastUpdate: 'Last Update',
      noData: 'No data found',
      loading: 'Loading...',
    },
    crafting: {
      title: 'Crafting Calculator',
      selectItem: 'Select Item',
      resources: 'Resources',
      totalCost: 'Total Cost',
      profit: 'Profit',
      profitMargin: 'Profit Margin',
      cityBonus: 'City Bonus',
      rrBonus: 'Resource Return Rate',
    },
    maps: {
      title: 'Maps',
      avalon: 'Avalon Roads',
      blackZone: 'Black Zone',
      redZone: 'Red Zone',
      yellowZone: 'Yellow Zone',
      blueZone: 'Blue Zone',
      searchMap: 'Search map...',
      tier: 'Tier',
      resources: 'Resources',
      hideouts: 'Hideouts',
      dungeons: 'Dungeons',
      portals: 'Portals',
      smartSort: 'Smart Sort',
      bestForCrafting: 'Best for Crafting',
      bestForGathering: 'Best for Gathering',
      bestForPvp: 'Best for PvP',
    },
    killboard: {
      title: 'Killboard',
      searchPlayer: 'Search player...',
      searchGuild: 'Search guild...',
      searchAlliance: 'Search alliance...',
      recentKills: 'Recent Kills',
      topKills: 'Top Kills',
      soloKills: 'Solo Kills',
      battles: 'Battles',
      fame: 'Fame',
      killFame: 'Kill Fame',
      deathFame: 'Death Fame',
    },
    builds: {
      title: 'Build Recommendations',
      solo: 'Solo',
      group: 'Group',
      dungeon: 'Dungeon',
      pvp: 'PvP',
      pve: 'PvE',
      ganking: 'Ganking',
      gathering: 'Gathering',
      healing: 'Healing',
      tanking: 'Tanking',
      dps: 'DPS',
      support: 'Support',
      aiRecommended: 'AI Recommended',
      selectActivity: 'Select Activity',
      selectGroupSize: 'Select Group Size',
      recommendedSet: 'Recommended Set',
      alternatives: 'Alternatives',
    },
    calculator: {
      title: 'Calculators',
      farming: 'Farming',
      laborers: 'Laborers',
      refining: 'Refining',
      journal: 'Journal',
      nutrition: 'Nutrition',
      association: 'Association',
    },
    common: {
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      create: 'Create',
      search: 'Search',
      filter: 'Filter',
      sort: 'Sort',
      refresh: 'Refresh',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      warning: 'Warning',
      info: 'Info',
      close: 'Close',
      open: 'Open',
      back: 'Back',
      next: 'Next',
      previous: 'Previous',
      confirm: 'Confirm',
      yes: 'Yes',
      no: 'No',
    },
  },
  de: {
    siteName: 'Albion Online Tools',
    siteDescription: 'Umfassende Tools und Guides für Albion Online',
    nav: {
      home: 'Startseite',
      market: 'Markt',
      crafting: 'Handwerk',
      maps: 'Karten',
      killboard: 'Killboard',
      builds: 'Builds',
      calculator: 'Rechner',
      settings: 'Einstellungen',
    },
    server: {
      title: 'Serverauswahl',
      description: 'Wählen Sie den Server für Datenabruf',
    },
    theme: {
      title: 'Thema',
      description: 'Anwendungsthema ändern',
    },
    language: {
      title: 'Sprache',
      description: 'Anwendungssprache ändern',
    },
    market: {
      title: 'Marktpreise',
      searchPlaceholder: 'Gegenstand suchen...',
      search: 'Suchen',
      city: 'Stadt',
      quality: 'Qualität',
      tier: 'Stufe',
      buyPrice: 'Kaufpreis',
      sellPrice: 'Verkaufspreis',
      lastUpdate: 'Letztes Update',
      noData: 'Keine Daten gefunden',
      loading: 'Laden...',
    },
    crafting: {
      title: 'Handwerksrechner',
      selectItem: 'Gegenstand wählen',
      resources: 'Ressourcen',
      totalCost: 'Gesamtkosten',
      profit: 'Gewinn',
      profitMargin: 'Gewinnspanne',
      cityBonus: 'Stadtbonus',
      rrBonus: 'Ressourcenrückgabe',
    },
    maps: {
      title: 'Karten',
      avalon: 'Avalon-Straßen',
      blackZone: 'Schwarze Zone',
      redZone: 'Rote Zone',
      yellowZone: 'Gelbe Zone',
      blueZone: 'Blaue Zone',
      searchMap: 'Karte suchen...',
      tier: 'Stufe',
      resources: 'Ressourcen',
      hideouts: 'Unterschlüpfe',
      dungeons: 'Verliese',
      portals: 'Portale',
      smartSort: 'Intelligente Sortierung',
      bestForCrafting: 'Beste für Handwerk',
      bestForGathering: 'Beste für Sammeln',
      bestForPvp: 'Beste für PvP',
    },
    killboard: {
      title: 'Killboard',
      searchPlayer: 'Spieler suchen...',
      searchGuild: 'Gilde suchen...',
      searchAlliance: 'Allianz suchen...',
      recentKills: 'Neueste Kills',
      topKills: 'Top Kills',
      soloKills: 'Solo Kills',
      battles: 'Schlachten',
      fame: 'Ruhm',
      killFame: 'Kill-Ruhm',
      deathFame: 'Todes-Ruhm',
    },
    builds: {
      title: 'Build-Empfehlungen',
      solo: 'Solo',
      group: 'Gruppe',
      dungeon: 'Verlies',
      pvp: 'PvP',
      pve: 'PvE',
      ganking: 'Ganking',
      gathering: 'Sammeln',
      healing: 'Heilung',
      tanking: 'Tanken',
      dps: 'DPS',
      support: 'Unterstützung',
      aiRecommended: 'KI-Empfohlen',
      selectActivity: 'Aktivität wählen',
      selectGroupSize: 'Gruppengröße wählen',
      recommendedSet: 'Empfohlenes Set',
      alternatives: 'Alternativen',
    },
    calculator: {
      title: 'Rechner',
      farming: 'Landwirtschaft',
      laborers: 'Arbeiter',
      refining: 'Veredelung',
      journal: 'Tagebuch',
      nutrition: 'Ernährung',
      association: 'Verband',
    },
    common: {
      save: 'Speichern',
      cancel: 'Abbrechen',
      delete: 'Löschen',
      edit: 'Bearbeiten',
      create: 'Erstellen',
      search: 'Suchen',
      filter: 'Filtern',
      sort: 'Sortieren',
      refresh: 'Aktualisieren',
      loading: 'Laden...',
      error: 'Fehler',
      success: 'Erfolg',
      warning: 'Warnung',
      info: 'Info',
      close: 'Schließen',
      open: 'Öffnen',
      back: 'Zurück',
      next: 'Weiter',
      previous: 'Zurück',
      confirm: 'Bestätigen',
      yes: 'Ja',
      no: 'Nein',
    },
  },
  fr: {
    siteName: 'Albion Online Tools',
    siteDescription: 'Outils et guides complets pour Albion Online',
    nav: {
      home: 'Accueil',
      market: 'Marché',
      crafting: 'Artisanat',
      maps: 'Cartes',
      killboard: 'Killboard',
      builds: 'Builds',
      calculator: 'Calculateur',
      settings: 'Paramètres',
    },
    server: {
      title: 'Sélection du Serveur',
      description: 'Sélectionnez le serveur pour récupérer les données',
    },
    theme: {
      title: 'Thème',
      description: 'Changer le thème de l\'application',
    },
    language: {
      title: 'Langue',
      description: 'Changer la langue de l\'application',
    },
    market: {
      title: 'Prix du Marché',
      searchPlaceholder: 'Rechercher un objet...',
      search: 'Rechercher',
      city: 'Ville',
      quality: 'Qualité',
      tier: 'Niveau',
      buyPrice: 'Prix d\'achat',
      sellPrice: 'Prix de vente',
      lastUpdate: 'Dernière mise à jour',
      noData: 'Aucune donnée trouvée',
      loading: 'Chargement...',
    },
    crafting: {
      title: 'Calculateur d\'Artisanat',
      selectItem: 'Sélectionner l\'objet',
      resources: 'Ressources',
      totalCost: 'Coût total',
      profit: 'Profit',
      profitMargin: 'Marge bénéficiaire',
      cityBonus: 'Bonus de ville',
      rrBonus: 'Taux de retour des ressources',
    },
    maps: {
      title: 'Cartes',
      avalon: 'Routes d\'Avalon',
      blackZone: 'Zone Noire',
      redZone: 'Zone Rouge',
      yellowZone: 'Zone Jaune',
      blueZone: 'Zone Bleue',
      searchMap: 'Rechercher une carte...',
      tier: 'Niveau',
      resources: 'Ressources',
      hideouts: 'Refuges',
      dungeons: 'Donjons',
      portals: 'Portails',
      smartSort: 'Tri intelligent',
      bestForCrafting: 'Meilleur pour l\'artisanat',
      bestForGathering: 'Meilleur pour la collecte',
      bestForPvp: 'Meilleur pour le PvP',
    },
    killboard: {
      title: 'Killboard',
      searchPlayer: 'Rechercher un joueur...',
      searchGuild: 'Rechercher une guilde...',
      searchAlliance: 'Rechercher une alliance...',
      recentKills: 'Kills récents',
      topKills: 'Meilleurs kills',
      soloKills: 'Kills solo',
      battles: 'Batailles',
      fame: 'Renommée',
      killFame: 'Renommée de kill',
      deathFame: 'Renommée de mort',
    },
    builds: {
      title: 'Recommandations de Builds',
      solo: 'Solo',
      group: 'Groupe',
      dungeon: 'Donjon',
      pvp: 'PvP',
      pve: 'PvE',
      ganking: 'Ganking',
      gathering: 'Collecte',
      healing: 'Soin',
      tanking: 'Tank',
      dps: 'DPS',
      support: 'Support',
      aiRecommended: 'Recommandé par IA',
      selectActivity: 'Sélectionner l\'activité',
      selectGroupSize: 'Sélectionner la taille du groupe',
      recommendedSet: 'Set recommandé',
      alternatives: 'Alternatives',
    },
    calculator: {
      title: 'Calculateurs',
      farming: 'Agriculture',
      laborers: 'Travailleurs',
      refining: 'Raffinage',
      journal: 'Journal',
      nutrition: 'Nutrition',
      association: 'Association',
    },
    common: {
      save: 'Sauvegarder',
      cancel: 'Annuler',
      delete: 'Supprimer',
      edit: 'Modifier',
      create: 'Créer',
      search: 'Rechercher',
      filter: 'Filtrer',
      sort: 'Trier',
      refresh: 'Actualiser',
      loading: 'Chargement...',
      error: 'Erreur',
      success: 'Succès',
      warning: 'Avertissement',
      info: 'Info',
      close: 'Fermer',
      open: 'Ouvrir',
      back: 'Retour',
      next: 'Suivant',
      previous: 'Précédent',
      confirm: 'Confirmer',
      yes: 'Oui',
      no: 'Non',
    },
  },
  es: {
    siteName: 'Albion Online Tools',
    siteDescription: 'Herramientas y guías completas para Albion Online',
    nav: {
      home: 'Inicio',
      market: 'Mercado',
      crafting: 'Artesanía',
      maps: 'Mapas',
      killboard: 'Killboard',
      builds: 'Builds',
      calculator: 'Calculadora',
      settings: 'Configuración',
    },
    server: {
      title: 'Selección de Servidor',
      description: 'Selecciona el servidor para obtener datos',
    },
    theme: {
      title: 'Tema',
      description: 'Cambiar tema de la aplicación',
    },
    language: {
      title: 'Idioma',
      description: 'Cambiar idioma de la aplicación',
    },
    market: {
      title: 'Precios del Mercado',
      searchPlaceholder: 'Buscar objeto...',
      search: 'Buscar',
      city: 'Ciudad',
      quality: 'Calidad',
      tier: 'Nivel',
      buyPrice: 'Precio de compra',
      sellPrice: 'Precio de venta',
      lastUpdate: 'Última actualización',
      noData: 'No se encontraron datos',
      loading: 'Cargando...',
    },
    crafting: {
      title: 'Calculadora de Artesanía',
      selectItem: 'Seleccionar objeto',
      resources: 'Recursos',
      totalCost: 'Costo total',
      profit: 'Ganancia',
      profitMargin: 'Margen de ganancia',
      cityBonus: 'Bonus de ciudad',
      rrBonus: 'Tasa de retorno de recursos',
    },
    maps: {
      title: 'Mapas',
      avalon: 'Caminos de Avalon',
      blackZone: 'Zona Negra',
      redZone: 'Zona Roja',
      yellowZone: 'Zona Amarilla',
      blueZone: 'Zona Azul',
      searchMap: 'Buscar mapa...',
      tier: 'Nivel',
      resources: 'Recursos',
      hideouts: 'Escondites',
      dungeons: 'Mazmorras',
      portals: 'Portales',
      smartSort: 'Ordenamiento inteligente',
      bestForCrafting: 'Mejor para artesanía',
      bestForGathering: 'Mejor para recolección',
      bestForPvp: 'Mejor para PvP',
    },
    killboard: {
      title: 'Killboard',
      searchPlayer: 'Buscar jugador...',
      searchGuild: 'Buscar gremio...',
      searchAlliance: 'Buscar alianza...',
      recentKills: 'Kills recientes',
      topKills: 'Mejores kills',
      soloKills: 'Kills solo',
      battles: 'Batallas',
      fame: 'Fama',
      killFame: 'Fama de kill',
      deathFame: 'Fama de muerte',
    },
    builds: {
      title: 'Recomendaciones de Builds',
      solo: 'Solo',
      group: 'Grupo',
      dungeon: 'Mazmorra',
      pvp: 'PvP',
      pve: 'PvE',
      ganking: 'Ganking',
      gathering: 'Recolección',
      healing: 'Sanación',
      tanking: 'Tanque',
      dps: 'DPS',
      support: 'Apoyo',
      aiRecommended: 'Recomendado por IA',
      selectActivity: 'Seleccionar actividad',
      selectGroupSize: 'Seleccionar tamaño de grupo',
      recommendedSet: 'Set recomendado',
      alternatives: 'Alternativas',
    },
    calculator: {
      title: 'Calculadoras',
      farming: 'Agricultura',
      laborers: 'Trabajadores',
      refining: 'Refinado',
      journal: 'Diario',
      nutrition: 'Nutrición',
      association: 'Asociación',
    },
    common: {
      save: 'Guardar',
      cancel: 'Cancelar',
      delete: 'Eliminar',
      edit: 'Editar',
      create: 'Crear',
      search: 'Buscar',
      filter: 'Filtrar',
      sort: 'Ordenar',
      refresh: 'Actualizar',
      loading: 'Cargando...',
      error: 'Error',
      success: 'Éxito',
      warning: 'Advertencia',
      info: 'Info',
      close: 'Cerrar',
      open: 'Abrir',
      back: 'Atrás',
      next: 'Siguiente',
      previous: 'Anterior',
      confirm: 'Confirmar',
      yes: 'Sí',
      no: 'No',
    },
  },
  ru: {
    siteName: 'Albion Online Tools',
    siteDescription: 'Комплексные инструменты и руководства для Albion Online',
    nav: {
      home: 'Главная',
      market: 'Рынок',
      crafting: 'Крафт',
      maps: 'Карты',
      killboard: 'Killboard',
      builds: 'Билды',
      calculator: 'Калькулятор',
      settings: 'Настройки',
    },
    server: {
      title: 'Выбор Сервера',
      description: 'Выберите сервер для получения данных',
    },
    theme: {
      title: 'Тема',
      description: 'Изменить тему приложения',
    },
    language: {
      title: 'Язык',
      description: 'Изменить язык приложения',
    },
    market: {
      title: 'Цены на Рынке',
      searchPlaceholder: 'Поиск предмета...',
      search: 'Поиск',
      city: 'Город',
      quality: 'Качество',
      tier: 'Уровень',
      buyPrice: 'Цена покупки',
      sellPrice: 'Цена продажи',
      lastUpdate: 'Последнее обновление',
      noData: 'Данные не найдены',
      loading: 'Загрузка...',
    },
    crafting: {
      title: 'Калькулятор Крафта',
      selectItem: 'Выбрать предмет',
      resources: 'Ресурсы',
      totalCost: 'Общая стоимость',
      profit: 'Прибыль',
      profitMargin: 'Маржа прибыли',
      cityBonus: 'Бонус города',
      rrBonus: 'Возврат ресурсов',
    },
    maps: {
      title: 'Карты',
      avalon: 'Дороги Авалона',
      blackZone: 'Чёрная Зона',
      redZone: 'Красная Зона',
      yellowZone: 'Жёлтая Зона',
      blueZone: 'Синяя Зона',
      searchMap: 'Поиск карты...',
      tier: 'Уровень',
      resources: 'Ресурсы',
      hideouts: 'Укрытия',
      dungeons: 'Подземелья',
      portals: 'Порталы',
      smartSort: 'Умная сортировка',
      bestForCrafting: 'Лучшее для крафта',
      bestForGathering: 'Лучшее для сбора',
      bestForPvp: 'Лучшее для PvP',
    },
    killboard: {
      title: 'Killboard',
      searchPlayer: 'Поиск игрока...',
      searchGuild: 'Поиск гильдии...',
      searchAlliance: 'Поиск альянса...',
      recentKills: 'Последние убийства',
      topKills: 'Лучшие убийства',
      soloKills: 'Соло убийства',
      battles: 'Битвы',
      fame: 'Слава',
      killFame: 'Слава убийств',
      deathFame: 'Слава смертей',
    },
    builds: {
      title: 'Рекомендации Билдов',
      solo: 'Соло',
      group: 'Группа',
      dungeon: 'Подземелье',
      pvp: 'PvP',
      pve: 'PvE',
      ganking: 'Ганкинг',
      gathering: 'Сбор',
      healing: 'Лечение',
      tanking: 'Танк',
      dps: 'DPS',
      support: 'Поддержка',
      aiRecommended: 'Рекомендовано ИИ',
      selectActivity: 'Выбрать активность',
      selectGroupSize: 'Выбрать размер группы',
      recommendedSet: 'Рекомендуемый сет',
      alternatives: 'Альтернативы',
    },
    calculator: {
      title: 'Калькуляторы',
      farming: 'Фермерство',
      laborers: 'Рабочие',
      refining: 'Переработка',
      journal: 'Журнал',
      nutrition: 'Питание',
      association: 'Ассоциация',
    },
    common: {
      save: 'Сохранить',
      cancel: 'Отмена',
      delete: 'Удалить',
      edit: 'Редактировать',
      create: 'Создать',
      search: 'Поиск',
      filter: 'Фильтр',
      sort: 'Сортировка',
      refresh: 'Обновить',
      loading: 'Загрузка...',
      error: 'Ошибка',
      success: 'Успех',
      warning: 'Предупреждение',
      info: 'Информация',
      close: 'Закрыть',
      open: 'Открыть',
      back: 'Назад',
      next: 'Далее',
      previous: 'Назад',
      confirm: 'Подтвердить',
      yes: 'Да',
      no: 'Нет',
    },
  },
  pt: {
    siteName: 'Albion Online Tools',
    siteDescription: 'Ferramentas e guias abrangentes para Albion Online',
    nav: {
      home: 'Início',
      market: 'Mercado',
      crafting: 'Artesanato',
      maps: 'Mapas',
      killboard: 'Killboard',
      builds: 'Builds',
      calculator: 'Calculadora',
      settings: 'Configurações',
    },
    server: {
      title: 'Seleção de Servidor',
      description: 'Selecione o servidor para buscar dados',
    },
    theme: {
      title: 'Tema',
      description: 'Alterar tema do aplicativo',
    },
    language: {
      title: 'Idioma',
      description: 'Alterar idioma do aplicativo',
    },
    market: {
      title: 'Preços do Mercado',
      searchPlaceholder: 'Pesquisar item...',
      search: 'Pesquisar',
      city: 'Cidade',
      quality: 'Qualidade',
      tier: 'Nível',
      buyPrice: 'Preço de compra',
      sellPrice: 'Preço de venda',
      lastUpdate: 'Última atualização',
      noData: 'Nenhum dado encontrado',
      loading: 'Carregando...',
    },
    crafting: {
      title: 'Calculadora de Artesanato',
      selectItem: 'Selecionar item',
      resources: 'Recursos',
      totalCost: 'Custo total',
      profit: 'Lucro',
      profitMargin: 'Margem de lucro',
      cityBonus: 'Bônus da cidade',
      rrBonus: 'Taxa de retorno de recursos',
    },
    maps: {
      title: 'Mapas',
      avalon: 'Estradas de Avalon',
      blackZone: 'Zona Negra',
      redZone: 'Zona Vermelha',
      yellowZone: 'Zona Amarela',
      blueZone: 'Zona Azul',
      searchMap: 'Pesquisar mapa...',
      tier: 'Nível',
      resources: 'Recursos',
      hideouts: 'Esconderijos',
      dungeons: 'Masmorras',
      portals: 'Portais',
      smartSort: 'Ordenação inteligente',
      bestForCrafting: 'Melhor para artesanato',
      bestForGathering: 'Melhor para coleta',
      bestForPvp: 'Melhor para PvP',
    },
    killboard: {
      title: 'Killboard',
      searchPlayer: 'Pesquisar jogador...',
      searchGuild: 'Pesquisar guilda...',
      searchAlliance: 'Pesquisar aliança...',
      recentKills: 'Kills recentes',
      topKills: 'Melhores kills',
      soloKills: 'Kills solo',
      battles: 'Batalhas',
      fame: 'Fama',
      killFame: 'Fama de kill',
      deathFame: 'Fama de morte',
    },
    builds: {
      title: 'Recomendações de Builds',
      solo: 'Solo',
      group: 'Grupo',
      dungeon: 'Masmorra',
      pvp: 'PvP',
      pve: 'PvE',
      ganking: 'Ganking',
      gathering: 'Coleta',
      healing: 'Cura',
      tanking: 'Tank',
      dps: 'DPS',
      support: 'Suporte',
      aiRecommended: 'Recomendado por IA',
      selectActivity: 'Selecionar atividade',
      selectGroupSize: 'Selecionar tamanho do grupo',
      recommendedSet: 'Set recomendado',
      alternatives: 'Alternativas',
    },
    calculator: {
      title: 'Calculadoras',
      farming: 'Agricultura',
      laborers: 'Trabalhadores',
      refining: 'Refinamento',
      journal: 'Diário',
      nutrition: 'Nutrição',
      association: 'Associação',
    },
    common: {
      save: 'Salvar',
      cancel: 'Cancelar',
      delete: 'Excluir',
      edit: 'Editar',
      create: 'Criar',
      search: 'Pesquisar',
      filter: 'Filtrar',
      sort: 'Ordenar',
      refresh: 'Atualizar',
      loading: 'Carregando...',
      error: 'Erro',
      success: 'Sucesso',
      warning: 'Aviso',
      info: 'Info',
      close: 'Fechar',
      open: 'Abrir',
      back: 'Voltar',
      next: 'Próximo',
      previous: 'Anterior',
      confirm: 'Confirmar',
      yes: 'Sim',
      no: 'Não',
    },
  },
  it: {
    siteName: 'Albion Online Tools',
    siteDescription: 'Strumenti e guide complete per Albion Online',
    nav: {
      home: 'Home',
      market: 'Mercato',
      crafting: 'Artigianato',
      maps: 'Mappe',
      killboard: 'Killboard',
      builds: 'Build',
      calculator: 'Calcolatore',
      settings: 'Impostazioni',
    },
    server: {
      title: 'Selezione Server',
      description: 'Seleziona il server per recuperare i dati',
    },
    theme: {
      title: 'Tema',
      description: 'Cambia tema dell\'applicazione',
    },
    language: {
      title: 'Lingua',
      description: 'Cambia lingua dell\'applicazione',
    },
    market: {
      title: 'Prezzi di Mercato',
      searchPlaceholder: 'Cerca oggetto...',
      search: 'Cerca',
      city: 'Città',
      quality: 'Qualità',
      tier: 'Livello',
      buyPrice: 'Prezzo d\'acquisto',
      sellPrice: 'Prezzo di vendita',
      lastUpdate: 'Ultimo aggiornamento',
      noData: 'Nessun dato trovato',
      loading: 'Caricamento...',
    },
    crafting: {
      title: 'Calcolatore di Artigianato',
      selectItem: 'Seleziona oggetto',
      resources: 'Risorse',
      totalCost: 'Costo totale',
      profit: 'Profitto',
      profitMargin: 'Margine di profitto',
      cityBonus: 'Bonus città',
      rrBonus: 'Tasso di ritorno risorse',
    },
    maps: {
      title: 'Mappe',
      avalon: 'Strade di Avalon',
      blackZone: 'Zona Nera',
      redZone: 'Zona Rossa',
      yellowZone: 'Zona Gialla',
      blueZone: 'Zona Blu',
      searchMap: 'Cerca mappa...',
      tier: 'Livello',
      resources: 'Risorse',
      hideouts: 'Nascondigli',
      dungeons: 'Dungeon',
      portals: 'Portali',
      smartSort: 'Ordinamento intelligente',
      bestForCrafting: 'Migliore per artigianato',
      bestForGathering: 'Migliore per raccolta',
      bestForPvp: 'Migliore per PvP',
    },
    killboard: {
      title: 'Killboard',
      searchPlayer: 'Cerca giocatore...',
      searchGuild: 'Cerca gilda...',
      searchAlliance: 'Cerca alleanza...',
      recentKills: 'Kill recenti',
      topKills: 'Migliori kill',
      soloKills: 'Kill solo',
      battles: 'Battaglie',
      fame: 'Fama',
      killFame: 'Fama kill',
      deathFame: 'Fama morte',
    },
    builds: {
      title: 'Raccomandazioni Build',
      solo: 'Solo',
      group: 'Gruppo',
      dungeon: 'Dungeon',
      pvp: 'PvP',
      pve: 'PvE',
      ganking: 'Ganking',
      gathering: 'Raccolta',
      healing: 'Cura',
      tanking: 'Tank',
      dps: 'DPS',
      support: 'Supporto',
      aiRecommended: 'Raccomandato da IA',
      selectActivity: 'Seleziona attività',
      selectGroupSize: 'Seleziona dimensione gruppo',
      recommendedSet: 'Set raccomandato',
      alternatives: 'Alternative',
    },
    calculator: {
      title: 'Calcolatori',
      farming: 'Agricoltura',
      laborers: 'Lavoratori',
      refining: 'Raffinazione',
      journal: 'Giornale',
      nutrition: 'Nutrizione',
      association: 'Associazione',
    },
    common: {
      save: 'Salva',
      cancel: 'Annulla',
      delete: 'Elimina',
      edit: 'Modifica',
      create: 'Crea',
      search: 'Cerca',
      filter: 'Filtra',
      sort: 'Ordina',
      refresh: 'Aggiorna',
      loading: 'Caricamento...',
      error: 'Errore',
      success: 'Successo',
      warning: 'Avviso',
      info: 'Info',
      close: 'Chiudi',
      open: 'Apri',
      back: 'Indietro',
      next: 'Avanti',
      previous: 'Precedente',
      confirm: 'Conferma',
      yes: 'Sì',
      no: 'No',
    },
  },
  pl: {
    siteName: 'Albion Online Tools',
    siteDescription: 'Kompleksowe narzędzia i przewodniki do Albion Online',
    nav: {
      home: 'Strona Główna',
      market: 'Rynek',
      crafting: 'Rzemiosło',
      maps: 'Mapy',
      killboard: 'Killboard',
      builds: 'Buildy',
      calculator: 'Kalkulator',
      settings: 'Ustawienia',
    },
    server: {
      title: 'Wybór Serwera',
      description: 'Wybierz serwer do pobierania danych',
    },
    theme: {
      title: 'Motyw',
      description: 'Zmień motyw aplikacji',
    },
    language: {
      title: 'Język',
      description: 'Zmień język aplikacji',
    },
    market: {
      title: 'Ceny na Rynku',
      searchPlaceholder: 'Szukaj przedmiotu...',
      search: 'Szukaj',
      city: 'Miasto',
      quality: 'Jakość',
      tier: 'Poziom',
      buyPrice: 'Cena kupna',
      sellPrice: 'Cena sprzedaży',
      lastUpdate: 'Ostatnia aktualizacja',
      noData: 'Nie znaleziono danych',
      loading: 'Ładowanie...',
    },
    crafting: {
      title: 'Kalkulator Rzemiosła',
      selectItem: 'Wybierz przedmiot',
      resources: 'Zasoby',
      totalCost: 'Całkowity koszt',
      profit: 'Zysk',
      profitMargin: 'Marża zysku',
      cityBonus: 'Bonus miasta',
      rrBonus: 'Zwrot zasobów',
    },
    maps: {
      title: 'Mapy',
      avalon: 'Drogi Avalonu',
      blackZone: 'Strefa Czarna',
      redZone: 'Strefa Czerwona',
      yellowZone: 'Strefa Żółta',
      blueZone: 'Strefa Niebieska',
      searchMap: 'Szukaj mapy...',
      tier: 'Poziom',
      resources: 'Zasoby',
      hideouts: 'Kryjówki',
      dungeons: 'Lochy',
      portals: 'Portale',
      smartSort: 'Inteligentne sortowanie',
      bestForCrafting: 'Najlepsze do rzemiosła',
      bestForGathering: 'Najlepsze do zbierania',
      bestForPvp: 'Najlepsze do PvP',
    },
    killboard: {
      title: 'Killboard',
      searchPlayer: 'Szukaj gracza...',
      searchGuild: 'Szukaj gildii...',
      searchAlliance: 'Szukaj sojuszu...',
      recentKills: 'Ostatnie zabójstwa',
      topKills: 'Najlepsze zabójstwa',
      soloKills: 'Solo zabójstwa',
      battles: 'Bitwy',
      fame: 'Sława',
      killFame: 'Sława zabójstw',
      deathFame: 'Sława śmierci',
    },
    builds: {
      title: 'Rekomendacje Buildów',
      solo: 'Solo',
      group: 'Grupa',
      dungeon: 'Loch',
      pvp: 'PvP',
      pve: 'PvE',
      ganking: 'Ganking',
      gathering: 'Zbieranie',
      healing: 'Leczenie',
      tanking: 'Tankowanie',
      dps: 'DPS',
      support: 'Wsparcie',
      aiRecommended: 'Rekomendowane przez AI',
      selectActivity: 'Wybierz aktywność',
      selectGroupSize: 'Wybierz rozmiar grupy',
      recommendedSet: 'Rekomendowany zestaw',
      alternatives: 'Alternatywy',
    },
    calculator: {
      title: 'Kalkulatory',
      farming: 'Rolnictwo',
      laborers: 'Robotnicy',
      refining: 'Rafinacja',
      journal: 'Dziennik',
      nutrition: 'Odżywianie',
      association: 'Stowarzyszenie',
    },
    common: {
      save: 'Zapisz',
      cancel: 'Anuluj',
      delete: 'Usuń',
      edit: 'Edytuj',
      create: 'Utwórz',
      search: 'Szukaj',
      filter: 'Filtruj',
      sort: 'Sortuj',
      refresh: 'Odśwież',
      loading: 'Ładowanie...',
      error: 'Błąd',
      success: 'Sukces',
      warning: 'Ostrzeżenie',
      info: 'Info',
      close: 'Zamknij',
      open: 'Otwórz',
      back: 'Wstecz',
      next: 'Dalej',
      previous: 'Wstecz',
      confirm: 'Potwierdź',
      yes: 'Tak',
      no: 'Nie',
    },
  },
  zh: {
    siteName: 'Albion Online Tools',
    siteDescription: 'Albion Online 的综合工具和指南',
    nav: {
      home: '首页',
      market: '市场',
      crafting: '制作',
      maps: '地图',
      killboard: '击杀榜',
      builds: '配装',
      calculator: '计算器',
      settings: '设置',
    },
    server: {
      title: '服务器选择',
      description: '选择要获取数据的服务器',
    },
    theme: {
      title: '主题',
      description: '更改应用主题',
    },
    language: {
      title: '语言',
      description: '更改应用语言',
    },
    market: {
      title: '市场价格',
      searchPlaceholder: '搜索物品...',
      search: '搜索',
      city: '城市',
      quality: '品质',
      tier: '等级',
      buyPrice: '购买价格',
      sellPrice: '出售价格',
      lastUpdate: '最后更新',
      noData: '未找到数据',
      loading: '加载中...',
    },
    crafting: {
      title: '制作计算器',
      selectItem: '选择物品',
      resources: '资源',
      totalCost: '总成本',
      profit: '利润',
      profitMargin: '利润率',
      cityBonus: '城市加成',
      rrBonus: '资源返还率',
    },
    maps: {
      title: '地图',
      avalon: '阿瓦隆之路',
      blackZone: '黑区',
      redZone: '红区',
      yellowZone: '黄区',
      blueZone: '蓝区',
      searchMap: '搜索地图...',
      tier: '等级',
      resources: '资源',
      hideouts: '藏身处',
      dungeons: '地下城',
      portals: '传送门',
      smartSort: '智能排序',
      bestForCrafting: '最适合制作',
      bestForGathering: '最适合采集',
      bestForPvp: '最适合 PvP',
    },
    killboard: {
      title: '击杀榜',
      searchPlayer: '搜索玩家...',
      searchGuild: '搜索公会...',
      searchAlliance: '搜索联盟...',
      recentKills: '最近击杀',
      topKills: '顶级击杀',
      soloKills: '单杀',
      battles: '战斗',
      fame: '声望',
      killFame: '击杀声望',
      deathFame: '死亡声望',
    },
    builds: {
      title: '配装推荐',
      solo: '单人',
      group: '团队',
      dungeon: '地下城',
      pvp: 'PvP',
      pve: 'PvE',
      ganking: ' ganking',
      gathering: '采集',
      healing: '治疗',
      tanking: '坦克',
      dps: '输出',
      support: '辅助',
      aiRecommended: 'AI 推荐',
      selectActivity: '选择活动',
      selectGroupSize: '选择团队规模',
      recommendedSet: '推荐套装',
      alternatives: '替代方案',
    },
    calculator: {
      title: '计算器',
      farming: '农业',
      laborers: '工人',
      refining: '精炼',
      journal: '日志',
      nutrition: '营养',
      association: '协会',
    },
    common: {
      save: '保存',
      cancel: '取消',
      delete: '删除',
      edit: '编辑',
      create: '创建',
      search: '搜索',
      filter: '筛选',
      sort: '排序',
      refresh: '刷新',
      loading: '加载中...',
      error: '错误',
      success: '成功',
      warning: '警告',
      info: '信息',
      close: '关闭',
      open: '打开',
      back: '返回',
      next: '下一步',
      previous: '上一步',
      confirm: '确认',
      yes: '是',
      no: '否',
    },
  },
};

// ============================================================================
// CITY BONUSES DATA
// ============================================================================

export interface CityBonus {
  city: string;
  refining: { resource: string; bonus: number }[];
  crafting: { item: string; bonus: number }[];
}

export const cityBonuses: CityBonus[] = [
  {
    city: 'Fort Sterling',
    refining: [{ resource: 'Wood', bonus: 40 }],
    crafting: [
      { item: 'Hammer', bonus: 15 },
      { item: 'Spear', bonus: 15 },
      { item: 'Holy Staff', bonus: 15 },
      { item: 'Plate Helmet', bonus: 15 },
      { item: 'Cloth Armor', bonus: 15 },
    ],
  },
  {
    city: 'Lymhurst',
    refining: [{ resource: 'Fiber', bonus: 40 }],
    crafting: [
      { item: 'Sword', bonus: 15 },
      { item: 'Bow', bonus: 15 },
      { item: 'Arcane Staff', bonus: 15 },
      { item: 'Leather Helmet', bonus: 15 },
      { item: 'Leather Shoes', bonus: 15 },
    ],
  },
  {
    city: 'Bridgewatch',
    refining: [{ resource: 'Stone', bonus: 40 }],
    crafting: [
      { item: 'Crossbow', bonus: 15 },
      { item: 'Dagger', bonus: 15 },
      { item: 'Cursed Staff', bonus: 15 },
      { item: 'Plate Armor', bonus: 15 },
      { item: 'Cloth Shoes', bonus: 15 },
    ],
  },
  {
    city: 'Martlock',
    refining: [{ resource: 'Hide', bonus: 40 }],
    crafting: [
      { item: 'Axe', bonus: 15 },
      { item: 'Quarterstaff', bonus: 15 },
      { item: 'Frost Staff', bonus: 15 },
      { item: 'Plate Shoes', bonus: 15 },
      { item: 'Off-Hand', bonus: 15 },
    ],
  },
  {
    city: 'Thetford',
    refining: [{ resource: 'Ore', bonus: 40 }],
    crafting: [
      { item: 'Mace', bonus: 15 },
      { item: 'Nature Staff', bonus: 15 },
      { item: 'Fire Staff', bonus: 15 },
      { item: 'Leather Armor', bonus: 15 },
      { item: 'Cloth Helmet', bonus: 15 },
    ],
  },
  {
    city: 'Caerleon',
    refining: [],
    crafting: [
      { item: 'Gathering Gear', bonus: 15 },
      { item: 'Tool', bonus: 15 },
      { item: 'Food', bonus: 15 },
      { item: 'War Gloves', bonus: 15 },
      { item: 'Shapeshifter Staff', bonus: 15 },
    ],
  },
  {
    city: 'Brecilien',
    refining: [],
    crafting: [
      { item: 'Cape', bonus: 15 },
      { item: 'Bag', bonus: 15 },
      { item: 'Potion', bonus: 15 },
    ],
  },
];

// ============================================================================
// ITEM CATEGORIES
// ============================================================================

export const itemCategories = [
  { id: 'weapon', name: 'Weapons', icon: 'Sword' },
  { id: 'offhand', name: 'Off-Hands', icon: 'Shield' },
  { id: 'armor', name: 'Armor', icon: 'Shirt' },
  { id: 'head', name: 'Helmets', icon: 'HardHat' },
  { id: 'shoes', name: 'Shoes', icon: 'Footprints' },
  { id: 'cape', name: 'Capes', icon: 'Flag' },
  { id: 'bag', name: 'Bags', icon: 'Backpack' },
  { id: 'potion', name: 'Potions', icon: 'FlaskConical' },
  { id: 'food', name: 'Food', icon: 'UtensilsCrossed' },
  { id: 'mount', name: 'Mounts', icon: 'Horse' },
  { id: 'tool', name: 'Tools', icon: 'Wrench' },
  { id: 'resource', name: 'Resources', icon: 'Gem' },
];

// ============================================================================
// QUALITY LEVELS
// ============================================================================

export const qualityLevels = [
  { id: 1, name: 'Normal', color: '#9ca3af' },
  { id: 2, name: 'Good', color: '#22c55e' },
  { id: 3, name: 'Outstanding', color: '#3b82f6' },
  { id: 4, name: 'Excellent', color: '#a855f7' },
  { id: 5, name: 'Masterpiece', color: '#f59e0b' },
];

// ============================================================================
// TIERS
// ============================================================================

export const tiers = [
  { id: 'T1', name: 'Tier 1', level: 1 },
  { id: 'T2', name: 'Tier 2', level: 2 },
  { id: 'T3', name: 'Tier 3', level: 3 },
  { id: 'T4', name: 'Tier 4', level: 4 },
  { id: 'T5', name: 'Tier 5', level: 5 },
  { id: 'T6', name: 'Tier 6', level: 6 },
  { id: 'T7', name: 'Tier 7', level: 7 },
  { id: 'T8', name: 'Tier 8', level: 8 },
];

// ============================================================================
// CITIES
// ============================================================================

export const cities = [
  'Bridgewatch',
  'Caerleon',
  'Fort Sterling',
  'Lymhurst',
  'Martlock',
  'Thetford',
  'Brecilien',
];

// ============================================================================
// AVALON MAPS DATA (Sample - Full data will be loaded from API)
// ============================================================================

export interface AvalonMap {
  id: string;
  name: string;
  tier: number;
  resources: string[];
  hasHideout: boolean;
  hasDungeon: boolean;
  connections: string[];
  imageUrl?: string;
}

// ============================================================================
// BUILD TEMPLATES
// ============================================================================

export interface BuildTemplate {
  id: string;
  name: string;
  type: 'solo' | 'group' | 'dungeon' | 'pvp' | 'pve' | 'ganking' | 'gathering';
  groupSize?: number;
  description: string;
  equipment: {
    weapon: string;
    offhand?: string;
    head: string;
    armor: string;
    shoes: string;
    cape?: string;
    bag?: string;
    potion?: string;
    food?: string;
  };
  skills: {
    weapon: string[];
    head: string[];
    armor: string[];
    shoes: string[];
  };
  alternatives?: {
    weapon?: string[];
    armor?: string[];
  };
  stats: {
    damage: number;
    defense: number;
    mobility: number;
    sustain: number;
    difficulty: number;
  };
}

export const buildTemplates: BuildTemplate[] = [
  {
    id: 'solo-battleaxe',
    name: 'Solid Battle Axe',
    type: 'solo',
    description: 'Versatile solo build for open world and dungeons',
    equipment: {
      weapon: 'T8_MAIN_AXE',
      offhand: 'T8_OFF_SHIELD',
      head: 'T8_HEAD_PLATE_SET2',
      armor: 'T8_ARMOR_PLATE_SET2',
      shoes: 'T8_SHOES_PLATE_SET2',
      cape: 'T8_CAPE',
      bag: 'T8_BAG',
      potion: 'T8_POTION_HEAL',
      food: 'T8_MEAL_STEW',
    },
    skills: {
      weapon: ['Rending Strike', 'Rending Rage', 'Battle Rush'],
      head: ['Astral Projection', 'Energy Regain'],
      armor: [' Fury', 'Bloodlust'],
      shoes: ['Sprint', 'Quick Thinker'],
    },
    alternatives: {
      weapon: ['T8_MAIN_SPEAR', 'T8_MAIN_SWORD'],
    },
    stats: {
      damage: 8,
      defense: 7,
      mobility: 6,
      sustain: 8,
      difficulty: 4,
    },
  },
  {
    id: 'group-healer',
    name: 'Divine Healer',
    type: 'group',
    groupSize: 5,
    description: 'Primary healer for group dungeons and PvP',
    equipment: {
      weapon: 'T8_MAIN_HOLYSTAFF',
      offhand: 'T8_OFF_BOOK',
      head: 'T8_HEAD_CLOTH_SET1',
      armor: 'T8_ARMOR_CLOTH_SET1',
      shoes: 'T8_SHOES_CLOTH_SET1',
      cape: 'T8_CAPE',
      bag: 'T8_BAG',
      potion: 'T8_POTION_ENERGY',
      food: 'T8_MEAL_SANDWICH',
    },
    skills: {
      weapon: ['Flash Heal', 'Holy Blessing', 'Sacred Pulse'],
      head: ['Meditation', 'Energy Regain'],
      armor: ['Cleanse', 'Protection'],
      shoes: ['Sprint', 'Cooldown Reduction'],
    },
    stats: {
      damage: 3,
      defense: 5,
      mobility: 6,
      sustain: 10,
      difficulty: 6,
    },
  },
];

// ============================================================================
// APP CONFIG
// ============================================================================

export interface AppConfig {
  defaultServer: ServerType;
  defaultTheme: ThemeType;
  defaultLanguage: LanguageType;
  refreshInterval: number;
}

export const appConfig: AppConfig = {
  defaultServer: 'west',
  defaultTheme: 'dark',
  defaultLanguage: 'tr',
  refreshInterval: 300000, // 5 minutes
};

export default appConfig;
